version: '3.4'
services:
  db_development:
    build:
      context: .
      dockerfile: DOCKERFILE.db.development
    image: db_development
    ports:
      - 5439:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=local_elections
  api_development:
    build:
      context: .
      dockerfile: DOCKERFILE.api.development
    image: api_development
    command: ./bin/development-docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_development
    environment:
      - PROJECT_NAME=localelections
      - DEBUG=True
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=local_elections
      - POSTGRES_HOST=db_development
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=password
      - DJANGO_SECRET_KEY=R4ND0M_STR1NG
